# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemesSiteBuilder#theme-configuration for an example

name = "Hugo Analytics module"
license = "MIT"
licenselink = "https://github.com/yelosan/hugo-analytics/blob/master/LICENSE"
description = "A collection of web analytics code provided as a module for Hugo projects."

# The home page of the theme, where the source can be found.
homepage = "https://github.com/yelosan/hugo-analytics"

# If you have a running demo of the theme.
#demosite = "https://gohugo.io"

tags = ["analytics", "module"]
features = ["image", "instagram", "music", "quotebox", "scribd", "youtube"]

# If the theme has multiple authors
#authors = [
#  {name = "Name of author", homepage = "Website of author"},
#  {name = "Name of author", homepage = "Website of author"}
#]

# If the theme has a single author
[author]
  name = "YourOnly.One"
  homepage = "https://YourOnly.One"

# If porting an existing theme
#[original]
#  author = "Name of original author"
#  homepage = "His/Her website"
#  repo = "Link to source code of original theme"
